export const climate_data = {
  canary_islands: {
    name: 'Canary Islands',
    description:
      'The Canary Islands enjoy a year-round spring-like climate with minimal temperature fluctuations. The steady climate is beneficial for many health conditions, especially respiratory issues.',
    data: [
      {
        month: 0,
        humidity: 65,
        airQuality: 90,
        allergens: 20,
        temperature: 18,
      },
      {
        month: 1,
        humidity: 65,
        airQuality: 90,
        allergens: 25,
        temperature: 18,
      },
      {
        month: 2,
        humidity: 60,
        airQuality: 90,
        allergens: 35,
        temperature: 19,
      },
      {
        month: 3,
        humidity: 60,
        airQuality: 95,
        allergens: 45,
        temperature: 20,
      },
      {
        month: 4,
        humidity: 60,
        airQuality: 95,
        allergens: 40,
        temperature: 21,
      },
      {
        month: 5,
        humidity: 55,
        airQuality: 90,
        allergens: 30,
        temperature: 23,
      },
      {
        month: 6,
        humidity: 55,
        airQuality: 90,
        allergens: 25,
        temperature: 24,
      },
      {
        month: 7,
        humidity: 60,
        airQuality: 85,
        allergens: 20,
        temperature: 25,
      },
      {
        month: 8,
        humidity: 65,
        airQuality: 90,
        allergens: 25,
        temperature: 24,
      },
      {
        month: 9,
        humidity: 65,
        airQuality: 95,
        allergens: 30,
        temperature: 23,
      },
      {
        month: 10,
        humidity: 70,
        airQuality: 90,
        allergens: 25,
        temperature: 21,
      },
      {
        month: 11,
        humidity: 70,
        airQuality: 90,
        allergens: 20,
        temperature: 19,
      },
    ],
  },
  barcelona: {
    name: 'Barcelona',
    description:
      'Barcelona has a Mediterranean climate with moderate humidity year-round. Air quality can be affected by urban pollution, especially in summer. Spring has higher allergen levels due to pollen.',
    data: [
      {
        month: 0,
        humidity: 70,
        airQuality: 75,
        allergens: 15,
        temperature: 10,
      },
      {
        month: 1,
        humidity: 70,
        airQuality: 75,
        allergens: 20,
        temperature: 11,
      },
      {
        month: 2,
        humidity: 65,
        airQuality: 70,
        allergens: 45,
        temperature: 13,
      },
      {
        month: 3,
        humidity: 65,
        airQuality: 75,
        allergens: 65,
        temperature: 15,
      },
      {
        month: 4,
        humidity: 65,
        airQuality: 80,
        allergens: 70,
        temperature: 19,
      },
      {
        month: 5,
        humidity: 65,
        airQuality: 75,
        allergens: 50,
        temperature: 23,
      },
      {
        month: 6,
        humidity: 70,
        airQuality: 70,
        allergens: 35,
        temperature: 26,
      },
      {
        month: 7,
        humidity: 70,
        airQuality: 65,
        allergens: 30,
        temperature: 26,
      },
      {
        month: 8,
        humidity: 70,
        airQuality: 75,
        allergens: 35,
        temperature: 23,
      },
      {
        month: 9,
        humidity: 70,
        airQuality: 80,
        allergens: 30,
        temperature: 19,
      },
      {
        month: 10,
        humidity: 75,
        airQuality: 75,
        allergens: 20,
        temperature: 14,
      },
      {
        month: 11,
        humidity: 75,
        airQuality: 75,
        allergens: 15,
        temperature: 11,
      },
    ],
  },
  madrid: {
    name: 'Madrid',
    description:
      'Madrid has a continental Mediterranean climate with very hot, dry summers and cool winters. The low humidity in summer is beneficial for respiratory conditions, but high temperatures can be challenging.',
    data: [
      { month: 0, humidity: 65, airQuality: 70, allergens: 10, temperature: 6 },
      { month: 1, humidity: 60, airQuality: 70, allergens: 15, temperature: 8 },
      {
        month: 2,
        humidity: 55,
        airQuality: 65,
        allergens: 50,
        temperature: 11,
      },
      {
        month: 3,
        humidity: 50,
        airQuality: 70,
        allergens: 70,
        temperature: 14,
      },
      {
        month: 4,
        humidity: 45,
        airQuality: 75,
        allergens: 65,
        temperature: 18,
      },
      {
        month: 5,
        humidity: 40,
        airQuality: 65,
        allergens: 45,
        temperature: 24,
      },
      {
        month: 6,
        humidity: 35,
        airQuality: 60,
        allergens: 30,
        temperature: 28,
      },
      {
        month: 7,
        humidity: 35,
        airQuality: 55,
        allergens: 25,
        temperature: 28,
      },
      {
        month: 8,
        humidity: 40,
        airQuality: 65,
        allergens: 30,
        temperature: 24,
      },
      {
        month: 9,
        humidity: 50,
        airQuality: 75,
        allergens: 25,
        temperature: 17,
      },
      {
        month: 10,
        humidity: 60,
        airQuality: 70,
        allergens: 15,
        temperature: 11,
      },
      {
        month: 11,
        humidity: 65,
        airQuality: 70,
        allergens: 10,
        temperature: 7,
      },
    ],
  },
  andalusia: {
    name: 'Andalusia',
    description:
      'Andalusia has a Mediterranean climate with very hot summers and mild winters. The region has low humidity in summer months which can benefit respiratory conditions, but extreme heat can be challenging.',
    data: [
      {
        month: 0,
        humidity: 70,
        airQuality: 80,
        allergens: 15,
        temperature: 12,
      },
      {
        month: 1,
        humidity: 65,
        airQuality: 80,
        allergens: 25,
        temperature: 13,
      },
      {
        month: 2,
        humidity: 60,
        airQuality: 75,
        allergens: 55,
        temperature: 16,
      },
      {
        month: 3,
        humidity: 55,
        airQuality: 80,
        allergens: 70,
        temperature: 18,
      },
      {
        month: 4,
        humidity: 50,
        airQuality: 85,
        allergens: 60,
        temperature: 22,
      },
      {
        month: 5,
        humidity: 45,
        airQuality: 80,
        allergens: 40,
        temperature: 27,
      },
      {
        month: 6,
        humidity: 40,
        airQuality: 75,
        allergens: 25,
        temperature: 31,
      },
      {
        month: 7,
        humidity: 40,
        airQuality: 70,
        allergens: 20,
        temperature: 31,
      },
      {
        month: 8,
        humidity: 45,
        airQuality: 80,
        allergens: 25,
        temperature: 27,
      },
      {
        month: 9,
        humidity: 55,
        airQuality: 85,
        allergens: 30,
        temperature: 22,
      },
      {
        month: 10,
        humidity: 65,
        airQuality: 80,
        allergens: 20,
        temperature: 16,
      },
      {
        month: 11,
        humidity: 70,
        airQuality: 80,
        allergens: 15,
        temperature: 13,
      },
    ],
  },
  valencia: {
    name: 'Valencia',
    description:
      'Valencia has a Mediterranean climate with moderate humidity year-round. The coastal location provides good air quality, and the climate is generally favorable for respiratory conditions.',
    data: [
      {
        month: 0,
        humidity: 65,
        airQuality: 80,
        allergens: 15,
        temperature: 12,
      },
      {
        month: 1,
        humidity: 65,
        airQuality: 80,
        allergens: 25,
        temperature: 13,
      },
      {
        month: 2,
        humidity: 60,
        airQuality: 75,
        allergens: 50,
        temperature: 15,
      },
      {
        month: 3,
        humidity: 60,
        airQuality: 80,
        allergens: 65,
        temperature: 17,
      },
      {
        month: 4,
        humidity: 60,
        airQuality: 85,
        allergens: 60,
        temperature: 20,
      },
      {
        month: 5,
        humidity: 60,
        airQuality: 80,
        allergens: 45,
        temperature: 24,
      },
      {
        month: 6,
        humidity: 65,
        airQuality: 75,
        allergens: 30,
        temperature: 27,
      },
      {
        month: 7,
        humidity: 65,
        airQuality: 70,
        allergens: 25,
        temperature: 27,
      },
      {
        month: 8,
        humidity: 65,
        airQuality: 80,
        allergens: 30,
        temperature: 24,
      },
      {
        month: 9,
        humidity: 65,
        airQuality: 85,
        allergens: 25,
        temperature: 20,
      },
      {
        month: 10,
        humidity: 65,
        airQuality: 80,
        allergens: 20,
        temperature: 16,
      },
      {
        month: 11,
        humidity: 65,
        airQuality: 80,
        allergens: 15,
        temperature: 13,
      },
    ],
  },
  galicia: {
    name: 'Galicia',
    description:
      'Galicia has an Atlantic climate with higher humidity and rainfall. The air quality is excellent due to low pollution, but the high humidity may be challenging for some respiratory conditions.',
    data: [
      {
        month: 0,
        humidity: 80,
        airQuality: 85,
        allergens: 10,
        temperature: 10,
      },
      {
        month: 1,
        humidity: 75,
        airQuality: 85,
        allergens: 15,
        temperature: 11,
      },
      {
        month: 2,
        humidity: 75,
        airQuality: 80,
        allergens: 40,
        temperature: 13,
      },
      {
        month: 3,
        humidity: 70,
        airQuality: 85,
        allergens: 60,
        temperature: 14,
      },
      {
        month: 4,
        humidity: 70,
        airQuality: 90,
        allergens: 65,
        temperature: 16,
      },
      {
        month: 5,
        humidity: 70,
        airQuality: 90,
        allergens: 50,
        temperature: 19,
      },
      {
        month: 6,
        humidity: 70,
        airQuality: 85,
        allergens: 35,
        temperature: 21,
      },
      {
        month: 7,
        humidity: 70,
        airQuality: 85,
        allergens: 30,
        temperature: 21,
      },
      {
        month: 8,
        humidity: 75,
        airQuality: 90,
        allergens: 35,
        temperature: 20,
      },
      {
        month: 9,
        humidity: 75,
        airQuality: 90,
        allergens: 25,
        temperature: 17,
      },
      {
        month: 10,
        humidity: 80,
        airQuality: 85,
        allergens: 15,
        temperature: 13,
      },
      {
        month: 11,
        humidity: 80,
        airQuality: 85,
        allergens: 10,
        temperature: 11,
      },
    ],
  },
};

export const cities = [
  {
    name: 'Barcelona',
    coords: [2.1734, 41.3851],
    description:
      'Vibrant Catalan capital famed for Gaudí’s Sagrada Familia and Park Güell, its bustling La Rambla boulevard, and sunny city beaches.',
    images: [
      'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR3IHXcZZujouhu8dXgw16p3JAgh6XnkleW_o_AXcu4CdDWP9isW50CsRCHL8IRSlmyV6tAPeBtF_buoAAmukdH6U4FaZQC-hzEbgAIFA',
      'https://lh3.googleusercontent.com/gps-cs-s/AC9h4np8lJSMGsdgpRNbDG5JgePhhIjvErt4lYTQ2iB4AiUWtxFvNsMryK-IxeYt-JZ99rJEG9rvp58lFDX0cTtU6tUNUSJjXijDCCSiqJ6mYOOkIdQK7VPwtTLa729ROIScZ1yPnAXPbg=w1080-h624-n-k-no',
      'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS2Khyxi-OLgopapzpevDYE7s89JPwjL7lX7yRjy8eVhHTyCu8hVPgxdcwv2mbdCaOwdP7gFwKrYAkHixu2QCWv8HXmMpqgn8vv2Hkb0Q',
    ],
    currentFactors: {
      humidity: 65,
      'air-quality': 75,
      allergens: 50,
      temperature: 23,
    },
    score: 8,
  },
  {
    name: 'Madrid',
    coords: [-3.7038, 40.4168],
    description:
      'Spain’s lively capital, home to world-class art museums (Prado, Reina Sofía), the grand Royal Palace, and expansive Retiro Park.',
    images: [
      'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRj4tANRJ5wpNkaVnA6PVIbzDPTJIaWXZVRE-6GTMTW_nSIo_qbWJfIEczZ6aiVzFXBU__Uz1cDv3qLTUCT1SkR-4l28y83GMGXUhTBJA',
      'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSmHvZhDsjfwKQuqlrN6ZRaUX36t084GdQx5SB_PKFWGSPK1WJGBkWzANGTkmcOBF7qAAJbsAszOyyogkPMgcAF9xERa11Yn801TdNJ0A',
      'https://lh3.googleusercontent.com/gps-cs-s/AC9h4norITrkEP3dCo8HDZhEg3_ryF6dXdAdojf0Z_tprEC28bzFZW_r90yzD5GXn1MY_Jo9JK3W_atgv7OCLw0MuKEYxaYk1IwYj-jRQVmw-StQsf66ixS-gA4_vTA1ug9jy0U7NSCm=w1080-h624-n-k-no',
    ],
    currentFactors: {
      humidity: 45,
      'air-quality': 75,
      allergens: 65,
      temperature: 18,
    },
    score: 7,
  },
  {
    name: 'Valencia',
    coords: [-0.3763, 39.4699],
    description:
      'Coastal city mixing futuristic architecture (City of Arts and Sciences) with a charming old town and world-famous paella.',
    images: [
      '/images/valencia-1.jpg',
      '/images/valencia-2.jpg',
      '/images/valencia-3.jpg',
    ],
    currenFactors: {
      humidity: 60,
      'air-quality': 80,
      allergens: 45,
      temperature: 24,
    },
    score: 5,
  },
  {
    name: 'Seville',
    coords: [-5.9845, 37.3891],
    description:
      'Andalusian gem known for the Alcázar palace, Gothic cathedral (housing Columbus’s tomb), flamenco performances, and orange-blossom streets.',
    images: [
      '/images/seville-1.jpg',
      '/images/seville-2.jpg',
      '/images/seville-3.jpg',
    ],
    currenFactors: {
      humidity: 60,
      'air-quality': 80,
      allergens: 45,
      temperature: 24,
    },
    score: 6,
  },
  {
    name: 'Granada',
    coords: [-3.5986, 37.1773],
    description:
      'Historic city at the foot of the Sierra Nevada, anchored by the Moorish Alhambra palace-fortress and atmospheric Albaicín quarter.',
    images: [
      'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQk8KeK_H48mFtgLF1_w3RimA6hmg8UIf7sE0iq9Wp5eEQs7sFVyN08bCZuysl2sw7hY9D3sIxh47A5CTGAG6UDj4IVeu7V9GOtC4P5HA',
      'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRxOTQBjLt3480QFzkSlhnnZ0mQVZh4VVnDbBXXlvwv-ya_zuxGyBaKYYBzqp8r2MwBsVRnZl9a3ZJE9GST0V-vExD6FEYqBfT_7LLzBg',
      'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcS2ngel-TO7iFgmWm09Qjdgc_mMt3m0XBfnbh9nzW25M4utbZH0wpgJqQPFRhPLwKCzwN9yueU2uwAgWW5qPkI5oFAk3yDIfw5pAa5KuA',
    ],
    currentFactors: {
      humidity: 65,
      'air-quality': 75,
      allergens: 50,
      temperature: 23,
    },
    score: 5,
  },
  {
    name: 'Malaga',
    coords: [-4.4214, 36.7213],
    description:
      'Sun-soaked Costa del Sol hub, Picasso’s birthplace, with a revitalized port, hilltop Alcazaba, and year-round beach life.',
    images: [
      'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQonNd-Ilx9dJGvdWVXO8WwGASontq4uLBPJM8gc9wwoOGdJ99Ml6-THKMtD4ddLyr79FtHdhZ2ONd4plDYXW9UIv8pZq5LBrTeSzigwQ',
      'https://lh3.googleusercontent.com/gps-cs-s/AC9h4nr2Dgmi7w9NvfwoA8986PRdzHc9rpOJIXWxy-bmA7d1_nSUYVu0pcDWi0Jm6X8zjYylpsjwhtEjaO8uHzM91iA-abcspdBA9ZU1_jm3TTjjjxKExsMz8ynJNWwJfOz5KJaZWuh6Lg=w1080-h624-n-k-no',
      'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRmMq91xq9E8f0tFx-4I1ZiL33p3h3GVxLt5eo9CwJAUrjsWdfm4IIMfqfYEDmVGLc75BpmoTR-LZqWFMTcHZkc39goX3zH3mEqo3UolQ',
    ],
    currentFactors: {
      humidity: 65,
      'air-quality': 75,
      allergens: 50,
      temperature: 23,
    },
    score: 5,
  },
  {
    name: 'Bilbao',
    coords: [-2.9349, 43.263],
    description:
      'Basque powerhouse defined by the Frank Gehry–designed Guggenheim Museum, a rich pintxo scene, and a riverside old town.',
    images: [
      '/images/bilbao-1.jpg',
      '/images/bilbao-2.jpg',
      '/images/bilbao-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Cordoba',
    coords: [-4.7794, 37.8882],
    description:
      'Once capital of Islamic Spain, famed for the Mezquita–Cathedral’s stunning arches, winding medieval lanes, and Roman bridge.',
    images: [
      '/images/cordoba-1.jpg',
      '/images/cordoba-2.jpg',
      '/images/cordoba-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Zaragoza',
    coords: [-0.8787, 41.6488],
    description:
      'Historic Ebro-river city with the baroque Basilica del Pilar, Aljafería Palace, and a vibrant tapas culture.',
    images: [
      '/images/zaragoza-1.jpg',
      '/images/zaragoza-2.jpg',
      '/images/zaragoza-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Alicante',
    coords: [-0.481, 38.3452],
    description:
      'Sunny Mediterranean port with a hilltop Castillo de Santa Bárbara, palm-lined Explanada promenade, and blue-flag beaches.',
    images: [
      '/images/alicante-1.jpg',
      '/images/alicante-2.jpg',
      '/images/alicante-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Palma de Mallorca',
    coords: [2.6502, 39.5696],
    description:
      'Majorca’s elegant capital, boasting a soaring Gothic cathedral, narrow old-town streets, and a scenic seaside boulevard.',
    images: [
      '/images/palma-de-mallorca-1.jpg',
      '/images/palma-de-mallorca-2.jpg',
      '/images/palma-de-mallorca-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Murcia',
    coords: [-1.1307, 37.9922],
    description:
      'Baroque-rich city on the Segura River, known for its cathedral’s ornate façade, lively plazas, and verdant orchards nearby.',
    images: [
      '/images/murcia-1.jpg',
      '/images/murcia-2.jpg',
      '/images/murcia-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'San Sebastian',
    coords: [-1.9812, 43.3183],
    description:
      'Gourmet paradise on the Bay of Biscay, famous for its La Concha beach, Monte Urgull views, and world-class pintxo bars.',
    images: [
      '/images/san-sebastian-1.jpg',
      '/images/san-sebastian-2.jpg',
      '/images/san-sebastian-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Salamanca',
    coords: [-5.6753, 40.9701],
    description:
      'University city with a UNESCO-listed Plaza Mayor, sandstone “Golden University” buildings, and a youthful, scholarly vibe.',
    images: [
      '/images/salamanca-1.jpg',
      '/images/salamanca-2.jpg',
      '/images/salamanca-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Toledo',
    coords: [-4.0244, 39.8628],
    description:
      '“City of Three Cultures” perched above the Tagus, with its Alcázar fortress, El Greco heritage, and labyrinthine medieval core.',
    images: [
      '/images/toledo-1.jpg',
      '/images/toledo-2.jpg',
      '/images/toledo-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Segovia',
    coords: [-4.1183, 40.947],
    description:
      'Characterful Castilian town crowned by a Roman aqueduct, fairy-tale Alcázar castle, and a Gothic cathedral set on a hilltop.',
    images: [
      '/images/segovia-1.jpg',
      '/images/segovia-2.jpg',
      '/images/segovia-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Cuenca',
    coords: [-2.1331, 40.0704],
    description:
      'Clifftop city famed for its UNESCO-listed hanging houses, dramatic gorge views, and a perfectly preserved medieval old town.',
    images: [
      '/images/cuenca-1.jpg',
      '/images/cuenca-2.jpg',
      '/images/cuenca-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Avila',
    coords: [-4.7069, 40.6565],
    description:
      'Walled Castilian city with complete 11th-century ramparts, Romanesque churches, and a famously austere, devotional atmosphere.',
    images: [
      '/images/avila-1.jpg',
      '/images/avila-2.jpg',
      '/images/avila-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Burgos',
    coords: [-3.6969, 42.3439],
    description:
      'Historic gateway to the Camino de Santiago, anchored by an impressive Gothic cathedral and a riverside medieval old quarter.',
    images: [
      '/images/burgos-1.jpg',
      '/images/burgos-2.jpg',
      '/images/burgos-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Oviedo',
    coords: [-5.8518, 43.3619],
    description:
      'Asturian capital known for its pre-Romanesque churches, elegant boulevard (La Calle Uría), and hearty cider-house culture.',
    images: [
      '/images/oviedo-1.jpg',
      '/images/oviedo-2.jpg',
      '/images/oviedo-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Santander',
    coords: [-3.8078, 43.4623],
    description:
      'Elegant Cantabrian port with the Palacio de la Magdalena on its bay, sandy beaches, and a refined seaside promenade.',
    images: [
      '/images/santander-1.jpg',
      '/images/santander-2.jpg',
      '/images/santander-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Tarragona',
    coords: [1.2546, 41.1189],
    description:
      'Roman-era seaside city boasting an amphitheatre by the sea, walled old town, and fresh seafood along the Mediterranean.',
    images: [
      '/images/tarragona-1.jpg',
      '/images/tarragona-2.jpg',
      '/images/tarragona-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Ronda',
    coords: [-5.1638, 36.7423],
    description:
      'Dramatic hilltop town split by El Tajo gorge, linked by its iconic Puente Nuevo bridge and surrounded by whitewashed villages.',
    images: [
      '/images/ronda-1.jpg',
      '/images/ronda-2.jpg',
      '/images/ronda-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Marbella',
    coords: [-4.8825, 36.5101],
    description:
      'Luxurious Costa del Sol resort town with upscale marinas (Puerto Banús), golden beaches, and a charming old quarter.',
    images: [
      '/images/marbella-1.jpg',
      '/images/marbella-2.jpg',
      '/images/marbella-3.jpg',
    ],
    score: 5,
  },
  {
    name: 'Girona',
    coords: [2.8214, 41.9794],
    description:
      'Medieval Catalan city with intact city walls, a labyrinthine Jewish quarter, and the colorful Onyar River façades.',
    images: [
      '/images/girona-1.jpg',
      '/images/girona-2.jpg',
      '/images/girona-3.jpg',
    ],
    score: 5,
  },
];
